name: saucectl cypress tests

on:
  pull_request:
  push:
    branches:
      - main

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}

jobs:
  steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Install saucectl