name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2020.3.32f1-android-1.0.1
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1

        - name: Decrypt the license file
          run: openssl aes-256-cbc -d -in .github/Unity_c2020.c.ulf.enc -k ${{ secrets.UNITY_LICENSE_DECRYPT_KEY }} >> .github/Unity_c2020.c.ulf
        
        # Activate unity
        - name: Activate Unity
          run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .github/Unity_c2020.c.ulf || exit 0
        - name: license
	    run: /opt/unity/Editor/Unity -quit -batchmode -nographics -logFile -serial ${{ secrets.UNITY_LICENSE_KEY }} -username '${{ secrets.UNITY_USERNAME }}' -password '${{ secrets.UNITY_PASSWORD }}'
        
        # Build Windows and OSX
        - name: Build Windows Player
          run: /opt/unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -noUpm -logFile -projectPath . -buildTarget Android ./bin-android/CISample.exe

        - name: Archive Windows Build
          uses: actions/upload-artifact@v1
          with:
            name: CISampleAndroidBinary
            path: ./bin-android

        # Return License       
	  - name: return License
	    run: /opt/unity/Editor/Unity -quit -batchmode -nographics -logFile -returnlicense -username ${{ secrets.UNITY_USERNAME }} -password ${{ secrets.UNITY_PASSWORD }}